language: objective-c
xcode_project: ObjectMapper+Realm.xcworkspace
xcode_scheme: ObjectMapper_RealmTests
install: 
  - pod repo update
  - pod install
after_success: 
  - bash <(curl -s https://codecov.io/bash) -J 'ObjectMapper_Realm'
